### ISSUE TITLE
Getting 10 gold does nothing

### ISSUE THREAD

**Issue by DanteDEVS** [DanteDEVS/MurderMysteryLED#11]
Getting 10 gold does completely nothing.

What it does: I get 10 gold it does nothing
What it supposed to do: I get 10 gold and get 1 bow & arrow {if the player is murderer or innocent they can get 1 boy & arrow}

**BUSY INVESTIGATING IT**

**SOLUTION? YOU KNOW HOW TO CODE? PULL REQUEST IT**

**THANKS :)**

**Comment by UnknownNull** [comment]
> Getting 10 gold does completely nothing.
> 
> What it does: I get 10 gold it does nothing What it supposed to do: I get 10 gold and get 1 bow & arrow {if the player is murderer or innocent they can get 1 boy & arrow}
> 
> **BUSY INVESTIGATING IT**
> 
> **SOLUTION? YOU KNOW HOW TO CODE? PULL REQUEST IT**
> 
> **THANKS :)**

I will help you, but you have to tell me what item you mean by these 2 lines below:

 if($item == 20112){
And
 if($item == 20019){
