### ISSUE TITLE
Throwable Sword

### ISSUE THREAD

**Issue by DanteDEVS** [DanteDEVS/MurderMysteryLED#13]
**Throwable Sword issue**

Currently if u right click it does not nothing sames goes in mobile if u use the block button or hold in with old controls, it does completely nothing, currently i have no fix for this but ill be investigating it.

If u have a solution dont mind pull requesting it thanks :)

**Comment by UnknownNull** [comment]
> **Throwable Sword issue**
> 
> Currently if u right click it does not nothing sames goes in mobile if u use the block button or hold in with old controls, it does completely nothing, currently i have no fix for this but ill be investigating it.
> 
> If u have a solution dont mind pull requesting it thanks :)

I can help you, but I'm afraid you will reject my pull request and do it yourself😂

**Comment by DanteDEVS** [comment]
lol

**Comment by DanteDEVS** [comment]
Ok so update on this i was so close into completing this however PMMP has an issue
[21:12:21.288] [Server thread/CRITICAL]: Error: "Call to undefined method pocketmine\network\mcpe\protocol\MobEquipmentPacket::getTypeId()" (EXCEPTION) in "pmsrc/vendor/pocketmine/bedrock-protocol/src/serializer/PacketSerializer" at line 453

which im pretty sure gotta do with PMMP themselves and not the code but im not sure, u can review my latest code and mabye you can find a way because im to tired researching on this new api

**Comment by UnknownNull** [comment]
> Ok so update on this i was so close into completing this however PMMP has an issue [21:12:21.288] [Server thread/CRITICAL]: Error: "Call to undefined method pocketmine\network\mcpe\protocol\MobEquipmentPacket::getTypeId()" (EXCEPTION) in "pmsrc/vendor/pocketmine/bedrock-protocol/src/serializer/PacketSerializer" at line 453
> 
> which im pretty sure gotta do with PMMP themselves and not the code but im not sure, u can review my latest code and mabye you can find a way because im to tired researching on this new api

was it fixed?

**Comment by DanteDEVS** [comment]
not sure i can test it out

**Comment by DanteDEVS** [comment]
latest commit may fix this issue idk

**Comment by DanteDEVS** [comment]
well new changes so basically know we need a new way to make the entity move as nbt is off our charts right now..
