### ISSUE TITLE
crash when killing with a bow

### ISSUE THREAD

**Issue by Smorted** [DanteDEVS/MurderMysteryLED#16]
PocketMine-MP Crash Dump Wed Jan 17 14:20:52 UTC 2024

PocketMine-MP version: 5.10.0 [Protocol 630]
Git commit: daeba95101e6278d1f2552397043d29d29d272f8
PHP version: 8.1.26
OS: Linux, linux

A PLUGIN WAS INVOLVED IN THIS CRASH
BAD PLUGIN: MurderMysteryLED

Thread: Main
Error: Typed property pocketmine\network\mcpe\protocol\SetSpawnPositionPacket::$spawnPosition must not be accessed before initialization
File: pmsrc/vendor/pocketmine/bedrock-protocol/src/SetSpawnPositionPacket
Line: 66
Type: Error
Backtrace:
#0 pmsrc/vendor/pocketmine/bedrock-protocol/src/DataPacket(84): pocketmine\network\mcpe\protocol\SetSpawnPositionPacket->encodePayload(object pocketmine\network\mcpe\protocol\serializer\PacketSerializer#76261)
#1 pmsrc/src/network/mcpe/NetworkSession(502): pocketmine\network\mcpe\protocol\DataPacket->encode(object pocketmine\network\mcpe\protocol\serializer\PacketSerializer#76261)
#2 pmsrc/src/network/mcpe/NetworkSession(483): pocketmine\network\mcpe\NetworkSession::encodePacketTimed(object pocketmine\network\mcpe\protocol\serializer\PacketSerializer#76261, object pocketmine\network\mcpe\protocol\SetSpawnPositionPacket#68939)
#3 plugins/MurderMysteryLED-main/src/mm/game/Game(819): pocketmine\network\mcpe\NetworkSession->sendDataPacket(object pocketmine\network\mcpe\protocol\SetSpawnPositionPacket#68939)
#4 plugins/MurderMysteryLED-main/src/mm/game/Game(792): mm\game\Game->setSpawnPositionPacket(object pocketmine\player\Player#155796, object pocketmine\math\Vector3#67329)
#5 plugins/MurderMysteryLED-main/src/mm/game/Game(689): mm\game\Game->killPlayer(object pocketmine\player\Player#187131, string[33] ..eYou killed an innocent player!)
#6 plugins/MurderMysteryLED-main/src/mm/game/Game(711): mm\game\Game->playerKillPlayer(object pocketmine\player\Player#187131, object pocketmine\player\Player#155796)
#7 pmsrc/src/event/RegisteredListener(61): mm\game\Game->onDamage(object pocketmine\event\entity\EntityDamageByChildEntityEvent#88851)
#8 pmsrc/src/event/Event(63): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\entity\EntityDamageByChildEntityEvent#88851)
#9 pmsrc/src/entity/Entity(530): pocketmine\event\Event->call()
#10 pmsrc/src/entity/Living(548): pocketmine\entity\Entity->attack(object pocketmine\event\entity\EntityDamageByChildEntityEvent#88851)
#11 pmsrc/src/player/Player(2466): pocketmine\entity\Living->attack(object pocketmine\event\entity\EntityDamageByChildEntityEvent#88851)
#12 pmsrc/src/entity/projectile/Projectile(298): pocketmine\player\Player->attack(object pocketmine\event\entity\EntityDamageByChildEntityEvent#88851)
#13 pmsrc/src/entity/projectile/Arrow(149): pocketmine\entity\projectile\Projectile->onHitEntity(object pocketmine\player\Player#155796, object pocketmine\math\RayTraceResult#88891)
#14 pmsrc/src/entity/projectile/Projectile(240): pocketmine\entity\projectile\Arrow->onHitEntity(object pocketmine\player\Player#155796, object pocketmine\math\RayTraceResult#88891)
#15 pmsrc/src/entity/Entity(997): pocketmine\entity\projectile\Projectile->move(float 1.4092843909644, float -0.10378671435724, float -2.5466132656771)
#16 pmsrc/src/world/World(997): pocketmine\entity\Entity->onUpdate(int 5724)
#17 pmsrc/src/world/World(922): pocketmine\world\World->actuallyDoTick(int 5724)
#18 pmsrc/src/world/WorldManager(351): pocketmine\world\World->doTick(int 5724)
#19 pmsrc/src/Server(1805): pocketmine\world\WorldManager->tick(int 5724)
#20 pmsrc/src/Server(1687): pocketmine\Server->tick()
#21 pmsrc/src/Server(1065): pocketmine\Server->tickProcessor()
#22 pmsrc/src/PocketMine(341): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#6, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
#23 pmsrc/src/PocketMine(364): pocketmine\server()
#24 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)

Code:
[57] 	protected function decodePayload(PacketSerializer $in) : void{
[58] 		$this->spawnType = $in->getVarInt();
[59] 		$this->spawnPosition = $in->getBlockPosition();
[60] 		$this->dimension = $in->getVarInt();
[61] 		$this->causingBlockPosition = $in->getBlockPosition();
[62] 	}
[63] 
[64] 	protected function encodePayload(PacketSerializer $out) : void{
[65] 		$out->putVarInt($this->spawnType);
[66] 		$out->putBlockPosition($this->spawnPosition);
[67] 		$out->putVarInt($this->dimension);
[68] 		$out->putBlockPosition($this->causingBlockPosition);
[69] 	}
[70] 
[71] 	public function handle(PacketHandlerInterface $handler) : bool{
[72] 		return $handler->handleSetSpawnPosition($this);
[73] 	}
[74] }

===END CRASH DUMP===

**Comment by DanteDEVS** [comment]
well ive tested myself and havent got this issue before but ill check up on it

**Comment by Smorted** [comment]
and also collecting gold does nothing, i even set it to 5 and collected 15 but nothing happened

**Comment by DanteDEVS** [comment]
yep i know that, currently im paying attention to fixing throwable sword, but yeah im working on fix both of the issues right now.

**Comment by DanteDEVS** [comment]
ok so its happening cuz theres something wrong with compass directions basically that part of the code is to locate where the bow is for compass or players, right now i feel like using some other method to ill keep that feature on hold for know.
but ill soon like tomorrow or in a few days will do it. gold im working on a fix right now.

**Comment by DanteDEVS** [comment]
this is basically fixed with latest commits

**Comment by Smorted** [comment]
bro btw the fix for the gold is just simply getEntity() instead of getOrigin() because the pickup event extends EntityEvent, tho i know i might be too late
